!IFNDEF MIX_APP_PATH
MIX_APP_PATH=$(MAKEDIR)
!ENDIF

PRIV_DIR = $(MIX_APP_PATH)/priv
NIF_SO = $(PRIV_DIR)/expty.dll

C_SRC = $(MAKEDIR)\c_src
LIB_SRC = $(MAKEDIR)\lib
NIF_BUILD_DIR = $(MIX_APP_PATH)/cmake_expty

!IFNDEF CMAKE_BUILD_TYPE
CMAKE_BUILD_TYPE=Release
!ENDIF

!IF "$(HAVE_NINJA)" == "true"
CMAKE_GENERATOR_TYPE=Ninja
!ELSE
CMAKE_GENERATOR_TYPE=NMake Makefiles
!ENDIF

build: $(NIF_SO)

$(PRIV_DIR):
    @ if not exist "$(PRIV_DIR)" mkdir "$(PRIV_DIR)"

$(NIF_BUILD_DIR):
	@ if not exist "$(NIF_BUILD_DIR)" mkdir "$(NIF_BUILD_DIR)"

$(NIF_SO): $(PRIV_DIR) $(NIF_BUILD_DIR)
	@ if not exist "$(NIF_SO)" ( \
		cd "$(NIF_BUILD_DIR)" && \
		cmake "$(MAKEDIR)" -G "$(CMAKE_GENERATOR_TYPE)" \
		    -D CMAKE_INSTALL_PREFIX="$(PRIV_DIR)" \
			-D C_SRC="$(C_SRC)" \
			-D CMAKE_TOOLCHAIN_FILE="$(TOOLCHAIN_FILE)" \
			-D MIX_APP_PATH="$(MIX_APP_PATH)" \
			-D PRIV_DIR="$(PRIV_DIR)" \
			-D ERTS_INCLUDE_DIR="$(ERTS_INCLUDE_DIR)" && \
		cmake --build . $(MAKE_BUILD_FLAGS) --config "$(CMAKE_BUILD_TYPE)" && \
		cmake --install . --config "$(CMAKE_BUILD_TYPE)" \
	)

cleanup:
	@ if exist "$(PRIV_DIR)" rmdir /s /q "$(PRIV_DIR)"
	@ if exist "$(NIF_BUILD_DIR)" rmdir /s /q "$(NIF_BUILD_DIR)"
